(fun (min x y) (if (< x y) x y)))
min
(fun (fact n) (if (= n 0) 1 (* n (fact (- n 1)))))) 
(fun (gcd m n) (if (= n 0) m (gcd n (% m n))))
(fun (length l) (if (null? l) 0 (+ 1 (length (rest l)))))
(fun (append l1 l2) (if (null? l1) l2 (cons (head l1) (append (rest l1) l2))))
(fun (ins-sort l) (do (fun (ins a l) (if (null? l) (cons (a) l) (do (def b (head l)) (if (< a b) (cons (a) l) (cons (b) (ins a (rest l))))))) (if (null? l) l (ins (head l) (ins-sort (rest l))))))
(def x 5)
(def y 10)
(def list (data (1 0 3 7 9 6 5)))
(def list1 (data (a b c)))
(min x y)　
(min y x)
(fact x)
(gcd x y)
(length list)
(append list1 list)
(ins-sort list)
